// GENERATED BY GenerateIconsMapPlugin
// DO NOT EDIT IT MANUALLY
  
export const svgIconsMap = {
  ArrowLong: () => import('./svg/arrow-long.svg'),
  Arrow: () => import('./svg/arrow.svg'),
  CalendarBase: () => import('./svg/calendar-base.svg'),
  Calendar: () => import('./svg/calendar.svg'),
  Check: () => import('./svg/check.svg'),
  Close: () => import('./svg/close.svg'),
  Copy: () => import('./svg/copy.svg'),
  EditBase: () => import('./svg/edit-base.svg'),
  EyeClosed: () => import('./svg/eye-closed.svg'),
  EyeOpen: () => import('./svg/eye-open.svg'),
  SearchBase: () => import('./svg/search-base.svg'),
  Search: () => import('./svg/search.svg'),
  Settings: () => import('./svg/settings.svg'),
} as const;
